// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSSERP;

#nullable disable

namespace NSSERP.Migrations
{
    [DbContext(typeof(YourDbContext))]
    [Migration("20231211061107_AddCountry")]
    partial class AddCountry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NSSERP.Areas.Masters.Models.Countrys", b =>
                {
                    b.Property<decimal>("Country_Code")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Country_CallCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Country_Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Currency_id")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Data_Flag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("FY_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Mob_Length")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Country_Code");

                    b.ToTable("COUNTRY_MASTER");
                });
#pragma warning restore 612, 618
        }
    }
}
